In [11]:
import keras

Using TensorFlow backend.


In [1]:
import numpy as np
np.random.seed(1337)  # for reproducibility
from keras.datasets import mnist
from keras.utils import np_utils
from keras.models import Sequential #一層一層的建立神經層
from keras.layers import Dense, Activation 
# layers.Dense表示這個神經層是全連接層
# layers.Activation 激勵函數
from keras.optimizers import RMSprop #優化器採用RMSprop，加速神經網絡訓練方法

Using TensorFlow backend.


In [2]:
# 載入數據：使用Keras本身的MNIST，分成訓練集和測試集
# x是圖片，y是突變對應的標籤（也就是數字）
(X_train, y_train), (X_test, y_test) = mnist.load_data()

In [3]:
# 對圖片轉成的數據做標準化(輸入的x變成60000*784的數據，除以255做標準化)
X_train = X_train.reshape(X_train.shape[0], -1) / 255.   # normalize
X_test = X_test.reshape(X_test.shape[0], -1) / 255.      # normalize

# y是數字0-9之間，現在是一個大小為10的向量，
#用one-hot-encoding轉換成0和1的形式 ex.數字2:0010000000
                                #   數字5:0000010000
y_train = np_utils.to_categorical(y_train, num_classes=10)
y_test = np_utils.to_categorical(y_test, num_classes=10)

In [4]:
print(X_train[1].shape)

#測試第一筆到第三筆
print(y_train[:3])

(784,)
[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]


In [5]:
# 建立模型
# 第一段加入Dense神經層，輸入784維度，輸出32維度，第一層傳出的數據有32個feature，傳給激勵函數
# 經過激勵函數之後，就變成了非線性的數據。
# 然後再把這個數據傳給下一個神經層，我們定義它有10個輸出的功能，接下來再輸入給下面的softmax函數，用來分類。
model = Sequential([
    Dense(32, input_dim=784),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])

In [6]:
# 用RMSprop作為優化器
rmsprop = RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)

In [7]:
# 激活模型
# metrics裡面可以放入需要計算的cost、accuracy、score等，這裡選擇accuracy準確度
model.compile(optimizer=rmsprop,
              loss='categorical_crossentropy',
              metrics=['accuracy'])


In [14]:
print('Training ------------')
# fit函數，把訓練集的x和y傳入之後，nb_epoch表示數據訓練的次數
#batch_size是每批處理的個數

model.fit(X_train, y_train, nb_epoch=5, batch_size=32)

Training ------------
Epoch 1/5
 1696/60000 [..............................] - ETA: 5s - loss: 0.0932 - acc: 0.9699

/Users/pengyuching/.pyenv/versions/3.5.2/lib/python3.5/site-packages/keras/models.py:844: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  warnings.warn('The `nb_epoch` argument in `fit` '


60000/60000 [==============================] - 4s - loss: 0.0950 - acc: 0.9740     
Epoch 2/5
60000/60000 [==============================] - 4s - loss: 0.0920 - acc: 0.9750     
Epoch 3/5
60000/60000 [==============================] - 4s - loss: 0.0876 - acc: 0.9759     
Epoch 4/5
60000/60000 [==============================] - 4s - loss: 0.0856 - acc: 0.9762     
Epoch 5/5
60000/60000 [==============================] - 4s - loss: 0.0822 - acc: 0.9775     


In [15]:
print('\nTesting ------------')
# 測試模型
loss, accuracy = model.evaluate(X_test, y_test)

print('test loss: ', loss)
print('test accuracy: ', accuracy) #準確度


Testing ------------
 8992/10000 [=========================>....] - ETA: 0stest loss:  0.13430336295
test accuracy:  0.9678
