In [9]:
import numpy as np

array = np.array([[1,2,3],[3,2,1]])
print(array)

[[1 2 3]
 [3 2 1]]


In [5]:
print('number of dim:',array.ndim) # 幾維
print("shape",array.shape) # 行列多少
print('size',array.size) # 幾個元素

number of dim: 2
shape (2, 3)
size 6


In [37]:
# 創立array
a = np.array([5,45,6],dtype = np.float) # 可設定 array 數據形式
print(a.dtype)

b = np.array([[55,33,2],[55,9,8]])
print(b)

c = np.zeros((3,4)) # 0 array
print(c)

d = np.empty((4,4)) # 接近 0 array
print(d)

e = np.arange(3,20,2)
print(e)

f = np.arange(18).reshape((3,6))
print(f)

g = np.linspace(1,10,5) # 生成線段
print(g)



float64
[[55 33  2]
 [55  9  8]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[ 3  5  7  9 11 13 15 17 19]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[  1.     3.25   5.5    7.75  10.  ]


In [43]:
a = np.array([10,20,30,40])
b = np.arange(4)
print(a,b)

c = a+b
print(c)

d = 10*np.cos(a)
print(d)

e = b < 3
e

[10 20 30 40] [0 1 2 3]
[10 21 32 43]
[-8.39071529  4.08082062  1.5425145  -6.66938062]


array([ True,  True,  True, False], dtype=bool)

In [52]:
# 陣列基礎運算
b = np.array([[5,3],[9,8]])
c = np.arange(4).reshape((2,2))
print(c)
# 逐個相乘
d = b*c
# 矩陣相乘
d_dot = np.dot(b,c)
print(d)
print(d_dot)

d_dot_2 = b.dot(c)
print(d_dot_2)

[[0 1]
 [2 3]]
[[ 0  3]
 [18 24]]
[[ 6 14]
 [16 33]]
[[ 6 14]
 [16 33]]


In [59]:
a = np.random.random((3,5)) # 隨機 array
print(a)

print(np.sum(a,axis=1))  # axis=1 每一列  axis=0 每一行
print(np.min(a))
print(np.max(a))

[[ 0.0632408   0.43623582  0.53368389  0.88228118  0.35261491]
 [ 0.88518687  0.77176127  0.5665305   0.70046129  0.13941173]
 [ 0.5677208   0.06333276  0.26484792  0.58657714  0.15529567]]
[ 2.26805659  3.06335166  1.63777429]
0.0632408033023
0.885186868715


In [81]:
# 陣列基礎運算
a = np.arange(2,14).reshape((3,4))
print(a)

print(np.argmin(a)) # 最小的索引直
print(np.mean(a))
print(np.median(a)) # 中位數
print(np.cumsum(a)) # 累加計算
print(np.diff(a)) # 累差
print(np.nonzero(a)) 
print(np.sort(a))
print(np.transpose(a)) # 行列交換
print((a.T).dot(a)) # 行列交換
print(np.clip(a,5,9)) # >5 =5 <9 =9
print(np.mean(a,axis=1))

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
7.5
7.5
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[[ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]
 [ 5  9 13]]
[[140 158 176 194]
 [158 179 200 221]
 [176 200 224 248]
 [194 221 248 275]]
[[5 5 5 5]
 [6 7 8 9]
 [9 9 9 9]]
[  3.5   7.5  11.5]


In [104]:
# numpy 索引
a = np.arange(3,15)
print(a)
print(a[3])

b = np.arange(3,15).reshape(3,4)
print(b)
print(b[2]) # 索引列數
print(b[1][2])
print(b[1,2])
print(b[1,:])
print(b[1,1:3])
print(b.flatten()) # 便 list


for row in b:
    print(row)
    
for col in b.T:  # 列轉行
    print(col)
    
for item in b.flat: # 列轉行
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
6
[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[11 12 13 14]
9
9
[ 7  8  9 10]
[8 9]
[ 3  4  5  6  7  8  9 10 11 12 13 14]
[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]
3
4
5
6
7
8
9
10
11
12
13
14


In [120]:
# array 合併
a = np.array([1,1,1,1])
b = np.array([2,2,2,2])

print(np.vstack((a,b))) # vertical stack 上下合併

c= np.vstack((a,b))
print(a.shape,c.shape) # 行列多少

print(np.hstack((a,b))) # horiaontal stack 左右合併
d= np.vstack((a,b))
print(a.shape,d.shape) # 行列多少

print(a[:,np.newaxis]) # 轉向
print(b[:,np.newaxis])
print(a.shape,b.shape)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 1 1 1]
 [2 2 2 2]]
(4,) (2, 4)
[1 1 1 1 2 2 2 2]
(4,) (2, 4)
[[1]
 [1]
 [1]
 [1]]
[[2]
 [2]
 [2]
 [2]]
(4,) (4,)
[[1 1 1 1]
 [2 2 2 2]]
[1 1 1 1 2 2 2 2]


In [128]:
a = np.array([1,1,1])[:,np.newaxis]
b = np.array([2,2,2])[:,np.newaxis]
c = np.concatenate((a,b,b,a),axis = 0)  # 多個 array 縱向或橫向合併
d = np.concatenate((a,b,b,a),axis = 1)
print(c)
print(d)

[[1]
 [1]
 [1]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [1]
 [1]
 [1]]
[[1 2 2 1]
 [1 2 2 1]
 [1 2 2 1]]


In [138]:
# 分割 array 

a = np.arange(12).reshape(3,4)
print(a)

print(np.split(a,2,axis = 1)) # 行分割2塊
print(np.split(a,3,axis = 0)) # 列分割3塊
print(np.array_split(a,3,axis = 1)) # 不等分割

print(np.hsplit(a,2)) # 行分割2塊
print(np.vsplit(a,3))# 列分割3塊


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


In [155]:
# copy deep copy

a = np.arange(4)
print(a)
b=a
print(b)
a[0] = 11  # 改變其中一個直都會便 copy
print(a)
print(b)

b = a.copy() # deep copy 把 a直給 b  沒把 b關連上 a
a[2] = 44
print(a)
print(b) # 值未改變

[0 1 2 3]
[0 1 2 3]
[11  1  2  3]
[11  1  2  3]
[11  1 44  3]
[11  1  2  3]
