## 瞭解 ndarray 的概觀

## ndim   屬性
## shape 屬性
## dtype  屬性

In [8]:
import numpy as np

irome = [33,66,77,22,444,11]
irome_array = np.array(irome)
print(irome_array.ndim)  # number of dimensions 維度
print(irome_array.shape) # m*n        求行列數
print(irome_array.dtype) # 資料類型

# 2D array
irome_2d = [range(1,7),[56,3,4,2,8,76]]
irome_2d_array = np.array(irome_2d)
print(irome_2d_array.ndim)  # number of dimensions 維度
print(irome_2d_array.shape) # m*n 
print(irome_2d_array.dtype) # 資料類型

1
(6,)
int64
2
(2, 6)
int64


## 建立 ndarray  
## numpy 套件除了 array() 方法可以將 list 轉換成 ndarray，還有其他的方法可以建立 ndarray

## zeros() 方法
## empty() 方法
## arange() 方法

In [9]:
import numpy as np
print(np.zeros(6)) # 六個元素均為零的 1d array
print("------") # 分隔線
print(np.zeros((2, 6))) # 十二個元素均為零的 2d array 2個6欄
print("------") # 分隔線
print(np.empty((2, 6, 2))) # 二十四個元素均為未初始化的值
print("------") # 分隔線
print(np.arange(11)) # 十一個元素為 0 到 10 的 1d array

[ 0.  0.  0.  0.  0.  0.]
------
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
------
[[[  6.91431254e-310   1.67942241e-316]
  [  6.91431316e-310   1.97626258e-323]
  [  1.69784118e-316   6.91430452e-310]
  [  6.91429783e-310   4.35218248e+111]
  [  0.00000000e+000   0.00000000e+000]
  [ -1.60688564e-062   0.00000000e+000]]

 [[  0.00000000e+000   4.05143130e-005]
  [  0.00000000e+000   0.00000000e+000]
  [  1.61269366e+047   0.00000000e+000]
  [  0.00000000e+000   1.75217237e+119]
  [  0.00000000e+000   0.00000000e+000]
  [  4.82039247e+097   0.00000000e+000]]]
------
[ 0  1  2  3  4  5  6  7  8  9 10]


## 轉換變數類型 
## ndarray 的 astype() 方法可以轉換變數類型

In [16]:
import numpy as np
irome = ["33","22","11","88","99"]
irome_str_array = np.array(irome)
print(irome_str_array.dtype)
print("----------------")
irome_int_array = irome_str_array.astype(np.int64)
print(irome_int_array.dtype) # 看資料類型

<U2
----------------
int64


## 用索引值進行篩選  利用 [ ] 搭配索引值篩選 ndarray

In [22]:
import numpy as np
my_array = np.arange(10) # arange 方法
print(my_array[0])
print(my_array[0:5])
print("----------")

my_2d_array = np.array([np.arange(0,5), np.arange(5,10)])
print(my_2d_array)
print("---------")
print(my_2d_array[1,:]) # 第二列
print(my_2d_array[:,1]) # 第二欄
print(my_2d_array[1,:1]) # 第二列 第二欄


0
[0 1 2 3 4]
----------
[[0 1 2 3 4]
 [5 6 7 8 9]]
---------
[5 6 7 8 9]
[1 6]
[5]


## 用布林值進行篩選  利用布林值（bool）篩選 ndarray

In [30]:
ironmen = [56, 8, 19, 14, 6, 71]
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", "Security", "自我挑戰組"]
ironmen_array = np.array(ironmen)
groups_array = np.array(groups)

# 用人數去篩選組別
print(ironmen_array >= 2) # 布林值陣列
print(groups_array[ironmen_array >= 10]) # 鐵人數大於 10 的組別


# 用組別去篩選人數
print(groups_array !="自我挑戰組") # 布林值陣列
print(ironmen_array[groups_array !="自我挑戰組"]) # 除了自我挑戰組織外的人數





[ True  True  True  True  True  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']
[ True  True  True  True  True False]
[56  8 19 14  6]


## 2d array 轉置


In [33]:
import numpy as np
# 建立2d array
m1_array = np.arange(10)
m2_array = m1_array.reshape((2,5))
print(m2_array)
print("---------")
print(m2_array.T) # T轉置矩陣

[[0 1 2 3 4]
 [5 6 7 8 9]]
---------
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


## numpy 的 where 方法
## 透過 numpy 的 where() 方法在 ndarray 中進行流程控制

In [34]:
import numpy as np

ironmen_array = np.array([56, 8, 19, 14, 6, np.nan])
np.where(np.isnan(ironmen_array), 71, ironmen_array)

array([ 56.,   8.,  19.,  14.,   6.,  71.])

## 排序

In [35]:
import numpy as np

ironmen_array = np.array([56, 8, 19, 14, 6, 71])
print(ironmen_array)
ironmen_array.sort()
print(ironmen_array)

[56  8 19 14  6 71]
[ 6  8 14 19 56 71]


## 隨機變數 透過 numpy 的 random() 方法可以生成隨機變數

In [36]:
import numpy as np

normal_samples = np.random.normal(size = 10) # 生成 10 組標準常態分配（平均值為 0，標準差為 1 的常態分配）隨機變數
uniform_samples = np.random.uniform(size = 10) # 生成 10 組介於 0 與 1 之間均勻分配隨機變數

print(normal_samples)
print("---") # 分隔線
print(uniform_samples)

[ 1.11763467  0.74138821 -1.14095274  1.06023478 -1.38327577  1.92824353
 -0.19510621 -0.97090254  0.27399516  0.79055409]
---
[ 0.70529289  0.98999491  0.7276108   0.98537907  0.40778381  0.03579847
  0.79984455  0.31519538  0.46398147  0.66392867]
